#!/usr/bin/env bash
declare -A pods
pods=(
    ["account"]="50001"
    ["admin-backend"]="50002"
    ["auth"]="50003"
    ["marketplace"]="50004"
    ["wallet"]="50005"
    ["otc-backend"]="50006"
    ["issuance"]="50007"
    ["atm-explorer"]="50008"
    ["backed-elements"]="50009"
    ["tx-executor"]="50010"
    ["financial-reporter"]="50011"
)


for pod in "${!pods[@]}"; do
    kubectl -n microservices get pods |
    grep -E "${pod}.*Running" |
    grep -vE 'migrations|vault' |
    head -n 1 |
    awk '{print $1;}' |
    xargs -I{} kubectl -n microservices port-forward --address 0.0.0.0 {} ${pods[$pod]}:50000 &
done

wait