#!/usr/bin/env bash
declare -A pods
pods=(
    # ["account"]="50001"
    # ["admin-backend"]="50002"
    # ["auth"]="50003"
    # ["marketplace"]="50004"
    # ["wallet"]="50005"
    # ["otc-backend"]="50006"
    # ["issuance"]="50007"
    # ["atm-explorer"]="50008"
    # ["backed-elements"]="50009"
    # ["tx-executor"]="50010"
    # ["financial-reporter"]="50011"
    # ["dictionary"]="50012"
    # ["agg-system"]="50013"
    # ["agg-user-profile"]="50014"
    # ["agg-customer-info"]="50015"
    # ["agg-wallet"]="50016"
    # ["agg-issuance"]="50017"
    # ["agg-primary-market"]="50018"
    ["external-gateway"]="50019"
)

for pod in "${!pods[@]}"; do
    kubectl -n microservices get pods |
    grep -E "${pod}.*Running" |
    grep -vE 'migrations|vault' |
    head -n 1 |
    awk '{print $1;}' |
    xargs -I{} kubectl -n microservices port-forward --address 0.0.0.0 {} ${pods[$pod]}:50000 &
done

wait